name: BUILD, TEST, AND DEPLOY TO Render

on:
    push:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Build Maven package
              run: mvn clean package -DskipTests

            - name: Log in to Docker Hub
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            - name: Build and push Docker image
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: |
                  IMAGE_NAME=$DOCKER_USERNAME/dil_api
                  docker build -t $IMAGE_NAME .
                  docker push $IMAGE_NAME

            - name: Deploy to Render
              env:
                  DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                  curl -X POST "$DEPLOY_URL"
